### ISSUE TITLE
AcceptDenyDialog  not working in API Level 23

### ISSUE THREAD

**Issue by Scienticious** [googlesamples/android-WearAccessibilityApp#2]
AcceptDenyDialog perfectly working in After API 23,
But oneActionDialog.get().show showing the warning i.e Call requires API Level 24
How to Show AcceptDenyDialog in API 23 , is there alternative ?

**Comment by codingjeremy** [comment]
This issue/PR has been migrated to the new Wear OS repo (linked above), so I am closing it here.
